version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.7.1
    - 3.9.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.7.0
    - 3.9.0
  - dependency-name: gatsby-cli
    versions:
    - 2.16.2
    - 2.18.0
  - dependency-name: gatsby-plugin-mdx
    versions:
    - 1.7.1
    - 1.9.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.11.2
    - 2.13.4
  - dependency-name: gatsby
    versions:
    - 2.29.3
    - 2.31.1
  - dependency-name: gatsby-image
    versions:
    - 2.10.0
    - 2.8.0
  - dependency-name: gatsby-remark-images
    versions:
    - 3.10.0
    - 3.8.1
  - dependency-name: gatsby-remark-smartypants
    versions:
    - 2.7.0
    - 2.9.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: acorn
    versions:
    - 6.4.1
